package deadlybanquet.speech;

/**
 * Created by Tom on 2016-04-06.
 */
public enum SpeechType {
    GREET,
    GOODBYE,
    WHERE_PERSON,
    WHERE_LOCATION,
    OPINION_QUESTION,
    INFO_P_OPINION,
    INFO_P_LOCATION,
    DONT_KNOW,
    EVENT_QUESTION_WHAT_ITEM,
    EVENT_INFO_DOER_WHAT_TIME_ITEM,
    EVENT_QUESTION_WHAT_RECEIVER,
    EVENT_INFO_DOER_WHAT_TIME_RECEIVER,
    EVENT_QUESTION_DOER_WHAT,
    EVENT_QUESTION_WHAT_DOER,
    EVENT_INFO_DOER_WHAT_ITEM,
    EVENT_INFO_RECEIVER_WHAT_DOER;
}
